# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_-]+$', 32), 'Invalid name. (hint: ^[a-zA-Z0-9_-]+$)')])),
                ('personal', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('resource_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ResourceGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_-]+$', 32), 'Invalid name. (hint: ^[a-zA-Z0-9_-]+$)')])),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resource_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api.ResourceGroup')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sitemembership',
            unique_together=set([('site', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('resource_group', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcegroupmembership',
            unique_together=set([('resource_group', 'user')]),
        ),
    ]
