# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('(?P<domain>[a-z0-9]+([-._~][a-z0-9]+)*)/(?P<name>[a-z0-9]+([-][a-z0-9]+)*):v(?P<version>(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:(?:\\d*[A-Za-z-][0-9A-Za-z-]*|(?:0|[1-9]\\d*))\\.)*(?:\\d*[A-Za-z-][0-9A-Za-z-]*|(?:0|[1-9]\\d*))))?(?:\\+((?:(?:[0-9A-Za-z-]+)\\.)*[0-9A-Za-z-]+))?)', 32), 'Invalid identifier.')])),
                ('manifest', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
